import type { ApplicationConfig } from './types';
/** Public application copy. Keep eligibility and shipped-work claims explicit. */
export const soundcloudApplication = {
  slug: 'soundcloud',
  company: 'SoundCloud',
  role: 'Senior Product Designer',
  focus: 'Creator Analytics & Tools',
  jobUrl: 'https://job-boards.greenhouse.io/soundcloud71/jobs/8755542002',
  sourceUrl: 'https://www.doorsopen.co/job/18433/senior-product-designer-creator-analytics-tools/',
  logo: '/applications/soundcloud/cloudmark.svg',
  ogImage: '/applications/soundcloud/share.png',
  cvUrl: '/giles-butler-soundcloud-cv.pdf',
  accent: '#ff5500',
  description: 'Giles Butler: product designer, design engineer and electronic music producer. Creator tools, product ownership and an interactive analytics exploration for SoundCloud. Requesting consideration from the UK.',
  greeting: 'hello, this is a story about…',
  heroQuestion: 'When we can make almost anything, how do we decide what is useful?',
  heroSummary: '15+ years designing and building software. 25+ years making electronic music. A founder’s experience of turning customer problems into shipped products.',
  locationShort: 'UK based · requesting an exception to the New York requirement',
  locationDetail: 'I understand this role is advertised as New York hybrid, not remote. I’m approaching SoundCloud to ask whether you would consider a UK-based exception. I have worked remotely for over ten years and can maintain overlap with New York; any arrangement would need your agreement.',
  whyTitle: 'The tools around the music matter too.',
  why: [
    'I know the work that goes into making and releasing a track. I’m interested in what happens next: helping an artist understand who is listening, what is changing and what is worth trying.',
    'Your Creator Analytics & Tools role combines that problem with the way I already work: define the product, investigate the workflow, design the interaction and stay involved through implementation. At Mixo and Mixvisor, product direction and engineering were part of the design job.',
    'For me, a useful dashboard starts with the creator’s question. A number needs a definition, a comparison and enough context to support a decision. A rise in plays is a reason to investigate, not proof of what caused it.',
  ],
  whyClose: 'I’d like to bring that combination of product ownership, design engineering and music experience to SoundCloud.',
  designHeading: 'A useful chart starts with a question.',
  designIntro: 'The same numbers can be presented as a report or organised around a decision. In this small exploration, switch the period and metric, then move between the overview and the underlying rows. The data stays the same; the hierarchy changes.',
  designCaption: 'Independent interaction exploration using fictional data. Not a SoundCloud product, API integration or customer-research finding.',
  designAfter: 'That is the part I want to test: does somebody understand the distinction, know where to look next and recognise the limits of what the data can tell them?',
  toolsParagraph: 'In an analytics interface, a plausible explanation is easy to write. Knowing whether the data supports it is a different task. I want tools that help a creator investigate, without pretending to know more than they do.',
  workIntro: 'An AI product built for non-technical business owners. A desktop app built from life in the studio. Two examples of owning both the product problem and the software.',
  workMixoRelevance: 'Independent product direction, customer-led discovery, complex SaaS workflows and the engineering to follow a decision through to release.',
  workMixvisorRelevance: 'First-hand understanding of creators, a useful model for messy information, and an entire desktop product designed and built from zero.',
  closing: 'I’d like to help artists make sense of what comes next.',
} as const satisfies ApplicationConfig;
